### PR TITLE
[cmake] Download NuGet instead of using from PATH

### PR DESCRIPTION
**Pull request by alexmercerind**
Just a little change, not really sure if an improvement. 
Since Android downloads whole more than hundred MB of Gradle for the first time, I don't think fetching 5 MB NuGet will annoy somebody.

### CODE REVIEW

**Comment by jnschulze** [comment]
Thanks!
From a security perspective, it should rather download a specific nuget version as opposed to the latest one and check its integrity (e.g. by using `file(SHA256 nuget.exe CHECKSUM)` and comparing `CHECKSUM` against the reference one).

**Comment by alexmercerind** [comment]
Is there any way to get GitHub actions working (if you are aware)? It just keeps using `10.0.17763.0`, I've tried to set up everything but it just doesn't use `10.0.19041.0`.

**Comment by jnschulze** [comment]
> Is there any way to get GitHub actions working (if you are aware)? It just keeps using `10.0.17763.0`, I've tried to set up everything but it just doesn't use `10.0.19041.0`. Any help.

I didn‘t get it working either when trying it a few weeks ago :(

**Comment by jnschulze** [comment]
I just made it work. The desired SDK version needs to be specified in the top-level CMake file (i.e. the examples's project file)

https://github.com/jnschulze/flutter-webview-windows/blob/5d0320cb4bdc398884dd2ecb2db4ebfab2817e86/example/windows/CMakeLists.txt#L3

**Pull request merged**
