### PR TITLE
Exposes and update some methods

### PR DESCRIPTION
**Pull request by Doflatango**
**CHANGELOG**

* Add method `addScriptToExecuteOnDocumentCreated` and `removeScriptToExecuteOnDocumentCreated` on `WebviewController`
* __Breaking change__ Update `WebViewController.webMessage` event type from `Map<dynamic, dynamic>` to `dynamic`
* Receive result of `executeScript`, add method `executeScriptStatement`

### CODE REVIEW

**Comment by Doflatango** [comment]
Related issues #161 #139  #69

**Comment by jnschulze** [comment]
Thanks! Would you mind creating a dedicated PR for each logical feature?

**Comment by Doflatango** [comment]
> Thanks! Would you mind creating a dedicated PR for each logical feature?

Yes, sure.

**Comment by venky9885** [comment]
Please merge it and release  new update ,i have to work on it

**Pull request closed without merging**
